### ISSUE TITLE
File  am-transmitter.grc can't open 

### ISSUE THREAD

**Issue by zzdts** [cleversonahum/gnuradio-am-transmission#5]
GNU Radio Companion 3.7.11 can't open am-transmitter.grc file:

Loading: "/home/rain/Downloads/gnuradio-am-transmission-master (1)/am-transmitter.grc"
Error: /home/rain/Downloads/gnuradio-am-transmission-master (1)/am-transmitter.grc:1:1:FATAL:PARSER:ERR_DOCUMENT_EMPTY: Start tag expected, '<' not found
>>> Failure

It's not a  XML file.

**Comment by cleversonahum** [comment]
Try to use the gnuradio 3.8. that's a gnuradio incompatibility
